name: Web Automation Testing
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Test URL'
        required: true
        type: string
      username:
        description: 'Login Username (optional)'
        required: false
        type: string
      password:
        description: 'Login Password (optional)'
        required: false
        type: string
      tests:
        description: 'Tests to run'
        required: false
        default: 'performance,security,forms,links,seo,accessibility'
        type: string

jobs:
  web-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create package.json in root
      run: |
        echo '{
          "name": "web-automation-runner",
          "version": "1.0.0",
          "description": "Web automation testing",
          "main": "automation/test-runner.js",
          "scripts": {
            "test": "node automation/test-runner.js"
          },
          "dependencies": {
            "playwright": "^1.40.0"
          }
        }' > package.json
        
    - name: Install dependencies
      run: npm install
        
    - name: Install Playwright browsers
      run: npx playwright install chromium
      
    - name: Run Web Automation Tests
      env:
        TEST_URL: ${{ github.event.inputs.url }}
        TEST_USERNAME: ${{ github.event.inputs.username }}
        TEST_PASSWORD: ${{ github.event.inputs.password }}
        TEST_TYPES: ${{ github.event.inputs.tests }}
      run: node automation/test-runner.js
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ github.run_number }}
        path: results/
